version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
    nodejs: "18"
  jobs:
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group dev --link-mode=copy

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Set the formats you want to build. Defaults to htmlzip and pdf.
formats:
  - htmlzip
  - epub
