name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.1
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Run Lint
        run: |
          uv run hatch run quality:check

      - name: Run Type Checks
        run: |
          uv run hatch run quality:typecheck

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    needs: formatting
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Run tests
        run: |
            uv run hatch run tests:run
